services:
  pa11y:
    build:
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    expose:
      - 27017
    command: --quiet
