services:
  pa11y:
    build:
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE=mongodb://mongodb/pa11y-webservice
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    expose:
      - 27017
    command: --quiet
