services:
  pa11ly:
    build:
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    expose:
      - 27017
    command: --quiet